In [1]:
import pandas as pd
from glob import glob
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:
files = glob('최종/*')

In [11]:
files

['최종\\최종발생01012206.csv', '최종\\최종사망0121.csv', '최종\\최종성별0121.csv']

In [14]:
for i in files:
    nm = i.split('\\')[1][2:4]
    globals()[f'{nm}'] = pd.read_csv(i)

In [15]:
발생

           연도  월  급수                   병  시도   군구  발생수
0        2001  1  1급            에볼라바이러스병  서울  강남구    0
1        2001  1  1급                마버그열  서울  강남구    0
2        2001  1  1급                 라싸열  서울  강남구    0
3        2001  1  1급           크리미안콩고출혈열  서울  강남구    0
4        2001  1  1급            남아메리카출혈열  서울  강남구    0
...       ... ..  ..                 ...  ..  ...  ...
4421083  2022  6  3급             진드기매개뇌염  세종  세종시    0
4421084  2022  6  3급                 유비저  세종  세종시    0
4421085  2022  6  3급              치쿤구니야열  세종  세종시    0
4421086  2022  6  3급  중증열성혈소판감소증후군(SFTS)  세종  세종시    0
4421087  2022  6  3급           지카바이러스감염증  세종  세종시    0

[4421088 rows x 7 columns]

In [16]:
사망

          연도    월  급수          병  시도  사망수
0       2001   1월  1급   에볼라바이러스병  강원  NaN
1       2001   2월  1급   에볼라바이러스병  강원  NaN
2       2001   3월  1급   에볼라바이러스병  강원  NaN
3       2001   4월  1급   에볼라바이러스병  강원  NaN
4       2001   5월  1급   에볼라바이러스병  강원  NaN
...      ...  ...  ..        ...  ..  ...
269887  2021   8월  3급  지카바이러스감염증  충북  0.0
269888  2021   9월  3급  지카바이러스감염증  충북  0.0
269889  2021  10월  3급  지카바이러스감염증  충북  0.0
269890  2021  11월  3급  지카바이러스감염증  충북  0.0
269891  2021  12월  3급  지카바이러스감염증  충북  0.0

[269892 rows x 6 columns]

In [18]:
성별

,연도,급수,병,시도,군구,0~4세_남,0~4세_여,5~9세_남,5~9세_여,10~14세_남,...,45~49세_남,45~49세_여,50~54세_남,50~54세_여,55~59세_남,55~59세_여,60~64세_남,60~64세_여,65세 이상_남,65세 이상_여
0,2001년,1급,에볼라바이러스병,서울,강남구,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2002년,1급,에볼라바이러스병,서울,강남구,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003년,1급,에볼라바이러스병,서울,강남구,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004년,1급,에볼라바이러스병,서울,강남구,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2005년,1급,에볼라바이러스병,서울,강남구,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359851,2017년,3급,지카바이러스감염증,세종,세종시,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
359852,2018년,3급,지카바이러스감염증,세종,세종시,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
359853,2019년,3급,지카바이러스감염증,세종,세종시,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
359854,2020년,3급,지카바이러스감염증,세종,세종시,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
359855,2021년,3급,지카바이러스감염증,세종,세종시,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
발생dir = glob('정형철교수님/*/')[-1]
files = glob(발생dir+'/*')

In [21]:
from tqdm import tqdm

In [22]:
for i in tqdm(files):
    dat = pd.read_csv(i, encoding = 'cp949', header = None).iloc[:,:-1]
    if dat.isnull().sum().sum() > 0:
        print(i)

100%|███████████████████████████████████████████████████████████████████████████████| 258/258 [00:01<00:00, 212.74it/s]

발생엔 애초에 null값이 없는 것을 확인.